### ISSUE TITLE
Where is the doc ? 

### ISSUE THREAD

**Issue by dridk** [niktto/easyemail#1]
Where is the doc ?

**Comment by niktto** [comment]
In repository there is only source for the docs, to generate HTML / epub / whatever you want - you'll need to run sphinx.

To run sphinx (http://sphinx-doc.org/tutorial.html) just go to `docs` folder and type:
`sphinx-build -b html sourcedir builddir` or use makefile from my repo (type `make html`)

I didn't want to generate all the possible output formats for this documentation, that is why there is just the source.
